### ISSUE TITLE
Pin map was wrong

### ISSUE THREAD

**Issue by keitetran** [jmichault/flash_cc2531#1]
Can u check pin map a gain ?

**Comment by bartekluk** [comment]
You have to connect reset to GPIO 16 the rest GPIO 19 and 20

**Comment by keitetran** [comment]
Thankyou.

typing gpio readall will show table pin map

https://pinout.xyz/

Pin 1 (GND)	-->	pin 39 (GND)
Pin 7 (reset)	-->	pin 19 (GPIO24)
Pin 3 (DC)	-->	pin 36 (GPIO27)
Pin 4 (DD)	-->	pin 38 (GPIO28)
