### ISSUE TITLE
Stuck on verifying

### ISSUE THREAD

**Issue by marrold** [jmichault/flash_cc2531#10]
Hi, I am trying to flash a CC2531 with a Raspberry Pi 1 B+ V1.2, however it's getting stuck on "verifying page" :

```
./cc_chipid
  ID = b524.
```

```
./cc_erase
  ID = b524.
  erase result = 00a2.
```

```
./cc_write CC2531ZNP-Prod.hex
  ID = b524.
  reading line 15490.
  file loaded (15497 lines read).
writing page 128/128.
verifying page   1/128.
```

**Comment by marrold** [comment]
Appears to work fine on a Raspberry Pi 3:

```
root@raspberrypi:/opt/flash_cc2531# ./cc_write CC2531ZNP-Prod.hex
  ID = b524.
  reading line 15490.
  file loaded (15497 lines read).
writing page 128/128.
verifying page 128/128.
 flash OK.
```

**Comment by luisapto702** [comment]
Im using raspberry pi4 and I tried several times flash cc2531 and all times occured problems in verifying page


`error at 0x0, 0x0 instead of 0xff
verifying page ........`

someone help me?

**Comment by imdos** [comment]
> Im using raspberry pi4 and I tried several times flash cc2531 and all times occured problems in verifying page
> 
> `error at 0x0, 0x0 instead of 0xff verifying page ........`
> 
> someone help me?

Try it with a USB(2.0) hub. There appear to be some problems with the Pi4 and it's USB3. I have read a post of problems with an Aeontec Z-wave stick and Pi4 which was solved with a hub.

**Comment by jmichault** [comment]
@luisapto702 
Can you retry with last release. It contains some changes in timings.

**Comment by ditek** [comment]
Related to this, verification after flashing the chip fails on RPi4 but succeeds on RPi3. I tried with the latest release.

**Comment by jbrocks** [comment]
I am having the same issue on RPi 3. Are there any solutions or workarounds? Should the stick work when quitting at verification time?

**Comment by jbrocks** [comment]
Okay found a quick solution for myself. I tried to flash using openhabian. Somehow this problem does not occur with my other SD card, with a clean Raspbian installation. Seems to be a software issue.

**Comment by kornikkk** [comment]
Hi, I'm having the same issue on Raspberry Pi B+ and the latest commit. cc_read also won't work. I checked out commit 65b94487c6a0ae38f57e1aa1a35d79129c815faa and everything works perfectly. Something must be wrong after this commit...

**Comment by wesselah** [comment]
I have excactly the same  issue verifing got stuck using the latest comment meaning using 65b9448 worked for me too.

**Comment by hmoffatt** [comment]
I had a verification failure with the latest release on Pi3, but I ran it again and it worked ok.

    pi@raspberrypi:~/src/flash_cc2531 $ ./cc_erase 
      ID = b524.
      erase result = 00a2.
    pi@raspberrypi:~/src/flash_cc2531 $ ./cc_write CC2531ZNP-Prod.hex
      ID = b524.
      reading line 15490.
      file loaded (15497 lines read).
    writing page 128/128.
    verifying page  91/128.
    error at 0x0, 0xe0 instead of 0x22
    verifying page 128/128.
     Errors found in 1 pages.
    pi@raspberrypi:~/src/flash_cc2531 $ ./cc_erase 
      ID = b524.
      erase result = 00a2.
    pi@raspberrypi:~/src/flash_cc2531 $ ./cc_write CC2531ZNP-Prod.hex
      ID = b524.
      reading line 15490.
      file loaded (15497 lines read).
    writing page 128/128.
    verifying page 128/128.
     flash OK.

**Comment by jdtsmith** [comment]
Same issue here with an RPI Zero W and Raspbian Buster. Any idea what would cause it to hang on:

> verifying page   1/128.

**Comment by jdtsmith** [comment]
Update: To avoid hanging on the "verifying page" during install on RPIZeroW Buster, I had to recompile with a "make". Then it works fine. Perhaps just remove the executables and have people compile their own version?

**Comment by nistvan86** [comment]
Going back to https://github.com/jmichault/flash_cc2531/commit/65b94487c6a0ae38f57e1aa1a35d79129c815faa solved it for me. Pi Zero, the older non W version. Recompiling HEAD was not enough.

**Comment by marrold** [comment]
Same issue with the Raspberry Pi 1 B+ V1.2 again. Reverted to 65b9448 as suggested and it's working.

**Comment by eon123** [comment]
I'm not so lucky as others here.  I'm getting the attached output when using a RPI 1B + V1.2 Sourcing with the latest version of the tools,, i.e. it's stuck at verifying page 1.  I tried reverting to [65b9448](https://github.com/jmichault/flash_cc2531/commit/65b94487c6a0ae38f57e1aa1a35d79129c815faa) as mentioned above but that version does not recognise the device at all and only outputs 0000's as the ID.  Any thoughts anyone? I am going to try and source a RPi2 to test with.

![image](https://user-images.githubusercontent.com/2719851/71102081-bb160f80-21af-11ea-8b46-564566865624.png)

**Comment by JoseAlcerreca** [comment]
Had the same problem in Rpi 1 B+ V1.2. Compiled master (just execute `make`) and it's working.

Verification is super slow though. I read the whole process would take 3 minutes but it's more like 1 page/minute.

**Comment by oscarlinux** [comment]
> Im using raspberry pi4 and I tried several times flash cc2531 and all times occured problems in verifying page
> 
> `error at 0x0, 0x0 instead of 0xff verifying page ........`
> 
> someone help me?

Hi, Were you able to make it work on rasberry PI 4? I keep getting id=ffff...   thanks!

**Comment by JakeMannen** [comment]
I needed to use the "-m 300" timings flag on my Pi B+ for this to work. Otherwise it got stuck at "Verifying page"
Good work here by the way!

**Comment by leventebalogh** [comment]
**How to use on Pi 3 Model B**

Just like @JakeMannen said as well before the `-m 300` flag was needed in order to make the commands work, otherwise they returned with `id=ffff`.

This is what worked for me:
```bash
# 1. Build (Optional)
$ make

# 2. Test
$ ./cc_chipid -m 300

# 3. Save the flash content
$ ./cc_read save.hex -m 300

# 4. Erase
$ ./cc_erase -m 300

# 5. Flash
./cc_write -m 300 CC2531ZNP-Pro.hex
```

After this it works like a charm, amazing work, thanks! 🙏

**Comment by waltner** [comment]
> I needed to use the "-m 300" timings flag on my Pi B+ for this to work. Otherwise it got stuck at "Verifying page"

Same here on a _Raspberry Pi 2 Model B Rev 1.1_. Thanks for the hint @JakeMannen ! :+1:
BTW, verification took about 2-3 sec per page.

**Comment by tdgeorge** [comment]
Rebuilding HEAD fixed the issue for me on a Pi 3B.

**Comment by Stefan300381** [comment]
another confirm that -m 300 fixed my frozen verification on raspberry Pi 1 Model B

**Comment by Strand1984** [comment]
another confirm that -m 300 fixed my frozen verification

**Comment by Staxen** [comment]
Confirm that -m 300 worked for my verifying error too...

verifying page   1/128.
error at 0x0, 0xff instead of 0x2
verifying page   2/128.
error at 0x0, 0xff instead of 0x8
verifying page   3/128.
error at 0x0, 0xff instead of 0x12

**Comment by Oddiwahn** [comment]
-m 300 worked for me as well on Rpi3 B+, thanks!
