### ISSUE TITLE
Update prerequisites (downdate?)

### ISSUE THREAD

**Issue by beikeland** [jmichault/flash_cc2531#12]
The[ prerequisites section ](https://github.com/jmichault/flash_cc2531#prerequisites)lists a Raspberry Pi 3, but it also works just fine on a Pi 1 RevB using the the commands in the [using other pins section.](https://github.com/jmichault/flash_cc2531#using-other-pins) A clearer presentation would be

- Raspberry Pi
- wiringpi

I almost didn't try this because the prerequisites lead me to believe it could not be done with a first or second gen Pi, which is plausible given arm6 vs arm7, processing power/ram, after all it talks about shutting down other software and other tips to improve performance.

That said; thanks for an awesome tool!

**Comment by jmichault** [comment]
You are right,

Done.
