### ISSUE TITLE
Directory not found using ubuntu on RPI 4b?

### ISSUE THREAD

**Issue by MikeZMssl** [jmichault/flash_cc2531#18]
Good afternoon,

After giving the command ./cc_chipid it says it cannot find the file or directory 
~/flash_cc2531$  ./cc_chipid
-bash: ./cc_chipid: No such file or directory

I do have WiringPi installed (gpio version: 2.50)
Does it have to do that I am running on Ubuntu 64 bit version (20.04 LTS) ?

Many thanks for your help!

**Comment by scaytrase** [comment]
Same problem here

**Comment by MikeZMssl** [comment]
A New sd card with raspbian lite did it for me!

**Comment by scaytrase** [comment]
I manager to install `libwiringpi-dev` and run `make` successfully. but got `0000.`. Checking my wires now

**Comment by Tobix99** [comment]
@scaytrase did you get it to work? Have the same problem under Ubuntu 20.04.1 LTS aarch64 on my Pi 3 B

**Comment by scaytrase** [comment]
If I remember correctly I moved to other flashing method. No luck with ubuntu 64 bit. I used wemos d1 mini (esp8266) as a intermediate flasher and then as a host device later.

https://zigbee.blakadder.com/flashing_ccloader.html

**Comment by Tobix99** [comment]
Ahh yes I couldn't got it working yesterday and used a Raspbian Lite Version like @MikeZMssl on another SD Card and this worked.

**Comment by albertmonzo** [comment]
This is because the version included in the repo is 32 bit, you have to recompike with `make`. If running on ubuntu/debian you will also have to sort out wiringPi, first by adding `iomem=relaxed` to `/boot/firmware/cmdline.txt` and then downloading this wiringPI fork, applying the [patch here](https://github.com/WiringPi/WiringPi/issues/108#issuecomment-817384407) and then compiling wiringPI with `./build`

**Comment by Bagunda** [comment]
Same problem. The file exists. But the bash writes about the absence.

![image](https://user-images.githubusercontent.com/16766521/178501424-6bd6763b-ea68-41c2-8259-7fa30df636ec.png)

**Comment by simonro0** [comment]
I had the same problem with raspbian 64bit. I just opened this repo called make and afterwards I received ID = 0000.
Without the 3.3V pin and inserted into a USB Port it returned ID = b524. and everything else worked as described.

**Comment by tswart-res** [comment]
> I had the same problem with raspbian 64bit. I just opened this repo called make and afterwards I received ID = 0000. Without the 3.3V pin and inserted into a USB Port it returned ID = b524. and everything else worked as described.

Thank you for this - 64bit on my pi zero w 2 and was stuck until you pointed out I had to run the make command first.
