### ISSUE TITLE
Flash of CC2531 hangs

### ISSUE THREAD

**Issue by jottr** [jmichault/flash_cc2531#20]
I am trying to flash the **CC2531** with the the [Z-Stack-firmware](https://github.com/Koenkk/Z-Stack-firmware) ([`CC2531_DEFAULT_20190608`](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/default)).

I have the **CC2531** connected to my RaspberryPI via GPIO-Pins (`Raspberry Pi Model B Rev 2`).

When trying to flash, `cc_write` hangs on the first page, see below:

```
# In TMUX, via SSH

./cc_chipid -c6 -r 10 -d 11 
  ID = b524.

./cc_erase  -c6 -r 10 -d 11 -m 600
  ID = b524.
  erase result = 00a2.

./cc_write CC2531ZNP-Prod.hex -c6 -r 10 -d 11 -m 600
  ID = b524.
  reading line 15490.
  file loaded (15497 lines read).
writing page   1/128.

```

I've played with the delay timing to no avail.

Trying to flash back the original firmware results in the same issue - the flashing process gets stuck on page 1:

```
./cc_write save.hex  -c6 -r 10 -d 11 -m 300
  ID = b524.
  reading line 530.
  file loaded (539 lines read).
writing page   1/  5.
```

**Comment by Jaren15949** [comment]
I'm having the exactly same problem with the same pi board
@beikeland, could you please let us know what we are doing wrong?

**Comment by jottr** [comment]
Is anyone here who can help?
@beikeland maybe?

**Comment by jottr** [comment]
Switching from a rPi 4 to an old model B seems to have done the trick.
Got it to work on the older rPi.
Not sure how this can be explained. 
Anyways, it works now.

**Comment by ragusa87** [comment]
I have the same issue using an old raspberry (Raspberry Model B Revision 2). I was able to read and clear the firmware, but the writing hangs.

I did some test by changing the time base (`-m` flag) with no success.

**Comment by ragusa87** [comment]
I retried using a Raspberry PI 3B+, Revision: 03 and it works fine.

**Comment by g-gg** [comment]
Had the same problem on a older Raspberry Pi Model B+ V1.2 (hangs at 1/128) and fixed this issue by connecting the CC2531 to an external USB power supply. And voilà, it worked!

For the records: Default pin numbers and timing were fine. Cloned the repository from git, last commit was May 1, 2021.
