### ISSUE TITLE
Can't open file CC2531ZNP-Prod.hex.

### ISSUE THREAD

**Issue by MortenBrandstrup** [jmichault/flash_cc2531#23]
Running a Pi4 lite os.
thinks looks fine, until I try to flash:

pi@raspberrypi:~/flash_cc2531 $ ./cc_chipid
  ID = b524.
pi@raspberrypi:~/flash_cc2531 $ ./cc_read save.hex
  ID = b524.
 reading 256k/256kpi@raspberrypi:~/flash_cc2531 $ ./cc_erase
  ID = b524.
  erase result = 00a2.
**pi@raspberrypi:~/flash_cc2531 $ ./cc_write CC2531ZNP-Prod.hex
 Can't open file CC2531ZNP-Prod.hex
pi@raspberrypi:~/flash_cc2531 $ ./cc_chipid
  ID = b524.

**Comment by jmichault** [comment]
You need to download CC2531ZNP-Prod.hex from Z-Stack-firmware site :

https://github.com/Koenkk/Z-Stack-firmware/raw/master/coordinator/Z-Stack_Home_1.2/bin/default/
