### ISSUE TITLE
is it compatible with orangepi pc plus arm7 with WiringOP?

### ISSUE THREAD

**Issue by kirill-shershen** [jmichault/flash_cc2531#24]
Hey,
I have installed orangepi pc plus with WiringOP
gpio readall
![image](https://user-images.githubusercontent.com/5936611/113749365-43f0eb80-9712-11eb-9cd6-7e7a257b196d.png)
is it posible to flash my cc2531 with this set?

**Comment by kirill-shershen** [comment]
yes, it works on orangepi with WiringOP. I've checked it.

**Comment by stevoh6** [comment]
@kirill-shershen  could you please share link to wiringop repo/tutorial? I was trying to do it with orangepi, but I failed. So I went with esp option. Thanks.

**Comment by kirill-shershen** [comment]
> @kirill-shershen could you please share link to wiringop repo/tutorial? I was trying to do it with orangepi, but I failed. So I went with esp option. Thanks.

I've used this repo https://github.com/zhaolei/WiringOP.git with branch "h3".  
**gpio readall** to check it.
When i downloaded **flash_cc2531** i've launch "make" and then **cc_chipid** and it show me **ID = b524**.
then connect pins like on this picture
![image](https://user-images.githubusercontent.com/5936611/114055465-78db7a80-9899-11eb-9f79-d9b162dfd6a1.png)
RPI pin layout here very similar with orangepi pc plus.
then launch cc_write

**Comment by stevoh6** [comment]
@kirill-shershen thank you very much :-) Now I know, where I made mistake :-)
