### ISSUE TITLE
verification error

### ISSUE THREAD

**Issue by Willi-SV** [jmichault/flash_cc2531#33]
Hello,
I have the same problem that was discussed before in issue # 32.
Always get the message:
ID = b524.
reading line 15490.
file loaded (15497 lines read).
writing page 65/128.verification error... Have you erased before write ?
I tried with Rasberry PI B and Raspberry Pi Zero W.
Also tested wit -m 300. No changes.
Any new ideas ?

**Comment by jcdel09** [comment]
Hello,
yes i erased before write.  it's always the same.
I saw that my chip was a cc2531 F 128. I bought another USB key with a 256 and it worked.
Moreover I think it's not the programming which is in question, but erasing. After programming with error, I reread the program and I found that on the non-programming part, I found the code of the old program. my solution was to buy another key. good luck

**Comment by mark1828** [comment]
Same error here. Have you solved it yet?
