### ISSUE TITLE
Verification error

### ISSUE THREAD

**Issue by kottes** [jmichault/flash_cc2531#36]
:/home/pi/flash_cc2531# ./cc_erase
  ID = b524.
  erase result = 00a2.

After cc_erase , writing is stopped after 65 pages.
/home/pi/flash_cc2531# sudo ./cc_write -m 300 CC2531ZNP-Prod.hex
  ID = b524.
  reading line 15490.
  file loaded (15497 lines read).
writing page  65/128.verification error... Have you erased before write ?
I cannot find a solution on internet. What is going wrong

**Comment by jcdel09** [comment]
hello,
yes, i erased all. I think the problem is at the level of the chip I have a C2531 F128. I bought a new key with a C2531 F256 that I was able to program under the same conditions and which works.
