### ISSUE TITLE
Size of cc_delay variables

### ISSUE THREAD

**Issue by petrpulc** [jmichault/flash_cc2531#7]
Please prove me wrong, but if unsigned char is used as a type for cc_delay(), value of 200 is passed to the function and this value is multiplied by 50 in the function and stored to the same data type (unsigned char), the value inevitably overflows (to value of 16).

Is this a bug or a feature?

**Comment by jmichault** [comment]
Obviously a bug. thanks.

**Comment by jmichault** [comment]
Corrected.
