### ISSUE TITLE
cc2531 wrong ID

### ISSUE THREAD

**Issue by AdrienAA** [jmichault/flash_cc2531#8]
Hello,

I'm trying to flash my cc2531, but the ID returned after running "./cc_chipid" is "ID = 1fff ."
I don't know where could the problem be. I checked my wiring a hundred time an everything seems to be ok.

I have no idea what to do, can you help me please ?

**Comment by imdos** [comment]
You have probably twisted your cable (from the USB-stick to the downloader cable). I have experienced this as well.

Place the red side of the cable either both next to 1 or the other side around.

**Comment by AdrienAA** [comment]
Hello,

I finaly have time to come back on my Zigbee devices.

So, I tried everything (and also I have seen the problem of people twisting their cable, but I took care to put everything well. My problem remains the same. I even bought another CC2531 USB Dongle but nothing changes...
Do you have any idea of where I can investigate ?

Thanks for you help !

**Comment by AdrienAA** [comment]
Well, I have tried eveything. I reinstalled WiringPi, I checked everything in the wiring, but I still get as an ID : ffff
Does anyone have an idea ? I'm using a Raspberry Pi 3B+ with the latest version of raspbian and no SSH connection.

**Comment by imdos** [comment]
I've succesfully used it with a batch on a pi3b. I've had problems with my downloader cable though. After I got a new one it worked perfectly. Altough the cable seemed intact it didn't worked. 

Otherwise power could be an issue maybe? Do you power the USB-stick from the Pi itself and do you have an appropriate power supply?

**Comment by AdrienAA** [comment]
I bought a new cable for the stick, maybe this is the problem.
About the power supply I bought one specificaly for the Pi so I think I'm good.
If the problem is not the cable, what do you think I can do ?

**Comment by imdos** [comment]
Complain to the vendor of the stick? I've had two "debug locked" sticks myself. 
Maybe you could try to deduce the problem in your neighbourhood with someone who has a working environment?

**Comment by AdrienAA** [comment]
Did you find any solution to bypass the "debug lock" ?
I'm afraid I don't have anybody around me who can help me

**Comment by imdos** [comment]
No; not yet. I'm going to try once more with unitool from TI. I claimed my "broken" sticks with a dispute on Aliexpress. 

P.S. I saw your cross post [here](https://github.com/Koenkk/zigbee2mqtt/issues/2024)

**Comment by AdrienAA** [comment]
I will try to claim a broken stick.
Yes, I made a post on the official zigbee2mqtt git, to see if they could have any other information

**Comment by imdos** [comment]
Did you use SmartRF (v1) (on Windows) or unitool from ti.com?

For some USB-sticks which are failing with flash_cc2531 ([see this topic](https://github.com/jmichault/flash_cc2531/issues/9)), I can just flash them using a CC-Debugger and SmartRF on Windows 10 perfectly fine.

**Comment by AdrienAA** [comment]
Yes, I use SmartRF V1 on windows.
Is it possible to use it directly on raspbian ?

**Comment by imdos** [comment]
No SmartRF only works on Windows AFAIK. But you have to use the CC-debugger and such as explained [here](https://www.zigbee2mqtt.io/getting_started/flashing_the_cc2531.html). 

I've had 2 batches of cc2531 chips; one which I could flash with flash_cc2531 and my rPi3 and the others only through Windows,  CC-debugger and SmartRF. Which I explained in my [earlier post](https://github.com/jmichault/flash_cc2531/issues/8#issuecomment-535911549) above.

**Comment by fredrikgk** [comment]
Koenkk/zigbee2mqtt#2024 Impossible to flash CC2531

**Comment by fredrikgk** [comment]
More details here: [#2024](https://github.com/Koenkk/zigbee2mqtt/issues/2024)

**Comment by AdrienAA** [comment]
Hello !
I bought a new cable to connect the dongle to the CCdebugger some times ago. It just arrived and everything worked ! So apparently the problem was only due to the cable.
Thanks a lot for your help ! I'm still trying to figure out the next steps, but finally I can go forward :)
